### ISSUE TITLE
Mobile view of adr.github.io is broken

### ISSUE THREAD

**Issue by ahus1** [adr/adr.github.io#1]
When viewing the website on a mobile phone, there is a black bar on the right and the headings are truncated. 

A first analysis showed that the two last commits to the theme cause this. I'm unable to extract the intent of the two commits, so I don't know what they tried to achieve/prevent. 

Once the two commits would be rolled back, the two very long links in the text and at the end that can't be wrapped are problematic for the mobile view. They could be rewritten with a text representing the link, or they could be wrapped with zero-width-spaces.

(Phone is a Google Pixel with Android 8.1 and Chrome 67)

![screenshot_20180712-232816](https://user-images.githubusercontent.com/3957921/42660758-67fe41f2-862c-11e8-8b07-fd8e9f30f7b7.png)

**Comment by koppor** [comment]
We're not that into CSS, too. So we have to wait for someone joining [#hacktoberfest](https://hacktoberfest.digitalocean.com/) and diving into CSS.

**Comment by koppor** [comment]
Source of the theme: https://github.com/adr/slate

Aim of the theme: **sticky headings and anchors**

**Comment by ahus1** [comment]
Given some trial and error I now understand why the `margin-right: -500px` is in the theme: 

* Intended behavior: h2-headlines should stick to the top of the browser windows when scrolling down 
* Problem: Long headlines will wrap and the following shorter headline will only hide part of the long headline. 
* Fix: `margin-right` makes every heading a single line heading
* Side effects: adding the `margin-right` adds a horizontal scroll bar, and on mobile devices it also adds a black bar to the right side of the window.

I don't know how to fix this without the described side effects. Would you consider removing "sticky headings" from the theme to improve the experience for mobile users?

**Comment by koppor** [comment]
Thank you for the deep investigation! Isn't there a possibility to activate
some CSS only for desktop resolutions?

Alexander Schwartz <notifications@github.com> schrieb am Sa., 6. Okt. 2018,
15:40:

**Comment by ahus1** [comment]
I could add a media query like this: 

"Activate sticky heading only if the width of the browser window is minimum 500px" 

This assumes: there will be no wrapping headings in this case

Result: sticky heading on desktop, no sticky headings on mobile

WDYT?

**Comment by koppor** [comment]
Yeah! Better than current solution!

Alexander Schwartz <notifications@github.com> schrieb am Sa., 6. Okt. 2018,
16:37:

**Comment by ahus1** [comment]
I submitted a PR for this to the theme repo. 

Please note: the first H2 in the index.md in this repo is very long. It doesn't fit the content area of the theme and wraps.

My idea: mark extra long headings to avoid their stickiness - like this. 

```
{: .long}
## Lightweight Architectural Decision Records Should be Adopted
```

WDYT? How should long headings look like in desktop mode?

**Comment by koppor** [comment]
yeah, sure. Think, there cant be an automatism here
