### ISSUE TITLE
Add Loqbooq to tooling

### ISSUE THREAD

**Issue by jpeinelt** [adr/adr.github.io#17]
Disclaimer: I'm one of the founders of [Loqbooq](https://loqbooq.app)

While Loqbooq is maybe more in general a tool for maintaining decision logs, it's very much inspired by using ADRs in our projects before. We were just always missing the inclusion of project managers and designers. Loqbooq is a Web App with a Slack integration.

Maybe this could be an addition to the tooling part of your website (I'm happy to create a PR for it), if not, please close and ignore. Anyway, thanks for documenting ADRs, this definitely already helped me introducing ADRs to colleagues and with keeping projects successful before!

Cheers!

**Comment by koppor** [comment]
Sure, go ahead!

As of today, Loqbooq seems to have following fields:

- Title
- Description
- Owner
- Reviewers
- Due Date

![grafik](https://user-images.githubusercontent.com/1366654/133367405-3d7a649d-ee23-491b-8f19-ad75c913ae34.png)

Would be nice to see more of the functionality on the homepage. Will try for myself as soon as I find time!

**Comment by jpeinelt** [comment]
Hi,

that's a good point about the website, we also should update the images. Currently we support the fields

- Title
- Result
- Considerations
- Owner
- Reviewers
- Tags
- Due Date

I'm happy to hear what you think about it, in the mean time I'll open a PR.

Thanks!!
