### ISSUE TITLE
Suggestion: remove "software" where not required

### ISSUE THREAD

**Issue by docwhat** [adr/adr.github.io#27]
> As a person working on a project with software and hardware components, the usage of "software" on the adr.github.io page makes me think it only applies to software when it works just as well for hardware architectural decisions. 

I want my hardware engineers not to think this is for software engineering only.

**Comment by socadk** [comment]
Thanks for your comment and suggestion, @docwhat (and sorry for belated reply). Would you like to create a PR?

Very much in line with our intent to widen the scope a bit, see this post https://medium.com/olzzio/adr-any-decision-record-916d1b64b28d
