### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by AleksandrSokolov** [adr/adr.github.io#30]
Please provide license information for this project. Conditions of use, etc..

**Comment by socadk** [comment]
The [MADR](https://github.com/adr/madr) project (in this organization) has license information.

**Comment by koppor** [comment]
We added [MIT license](https://www.tldrlegal.com/license/mit-license). See https://github.com/adr/adr.github.io/tree/main.

I also added a link how to contribute to the page. I hope, this fulfills your needs @AleksandrSokolov.

**Comment by koppor** [comment]
![image](https://github.com/adr/adr.github.io/assets/1366654/8ae4db82-a8bb-4f99-b099-5f4968fc17d3)

**Comment by AleksandrSokolov** [comment]
@koppor Thank you!
